id: I72D813C4
legacy_id: P005643
ocr_import_info:
  bdrc_scan_id: W29514
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T03:27:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T13:48:45.687772+00:00'
last_modified: 2022-09-02 21:49:53.886451
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29514
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29514
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རྗེ་ཐེག་པའི་ལམ་གྱི་སྔོན་འགྲོའི་ཁྲིད་ཡིག
  author: ན་ལེནྡྲ་མཁན་ཆེན་ངག་དབང་བློ་གྲོས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.6972007063795238
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I1KG3576:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3576
      total_pages: 652
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3576.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.6972007063795238
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
